import { CSSProperties, MouseEventHandler } from "react"
import { IPropertiesCombobox } from "../components/ComboBox/ComboBox"
import { AccountIcon, ActionIcon, AdventureIcon, AnimationIcon, ArrowLeftIcon, BookmarkIcon, ComedyIcon, CrimeIcon, DocumentaryIcon, DramaIcon, FamilyIcon, FantasyIcon, FavoriteEmptyIcon, HistoryIcon, HomeIcon, HorrorIcon, KidIcon, LogInIcon, LogoutIcon, MovieIcon, MovieListIcon, MusicIcon, MysteryIcon, NewsIcon, PeopleIcon, RealityIcon, RomanceIcon, SCIFiIcon, SearchIcon, SerieIcon, SettingsIcon, SoapIcon, TVMovieIcon, TalkIcon, ThrillerIcon, WarIcon, WesternIcon } from "./svg"

export const MainMenu = [
    {
        id: 0,
        name: "Busqueda",
        link: "search",
        icon: <SearchIcon className="mainMenuLogo" />
    },
    {
        id: 1,
        name: "Inicio",
        link: "",
        icon: <HomeIcon className="mainMenuLogo" />
    },
    {
        id: 2,
        name: "Películas",
        link: "movies",
        icon: <MovieIcon className="mainMenuLogo" />
    },
    {
        id: 3,
        name: "Series",
        link: "series",
        icon: <SerieIcon className="mainMenuLogo" />
    },
    {
        id: 4,
        name: "Personas",
        link: "people",
        icon: <PeopleIcon className="mainMenuLogo" />
    },
    {
        id: 5,
        name: "Favoritos",
        link: "favorites",
        icon: <FavoriteEmptyIcon className="mainMenuLogo" />
    },
    {
        id: 6,
        name: "Listas",
        link: "lists",
        icon: <MovieListIcon className="mainMenuLogo" />
    },
    {
        id: 7,
        name: "Lista de seguimiento",
        link: "watchlist",
        icon: <BookmarkIcon className="mainMenuLogo" />
    },
    {
        id: 8,
        name: "Cuenta",
        link: "account",
        icon: <AccountIcon className="mainMenuLogo" />
    },
    {
        id: 9,
        name: "Configuración",
        link: "settings",
        icon: <SettingsIcon className="mainMenuLogo" />
    },
    {
        id: 10,
        name: "Cerrar sesión",
        link: "logout",
        icon: <LogoutIcon className="mainMenuLogo" />
    },
    {
        id: 11,
        name: "Iniciar sesión",
        link: "login",
        icon: <LogInIcon className="mainMenuLogo" />
    }
]

export const CategoriesMovies = [
    {
        id: 28,
        name: "Acción",
        link: "action",
        icon: <ActionIcon className="logo_category" />
    },
    {
        id: 12,
        name: "Aventura",
        link: "adventure",
        icon: <AdventureIcon className="logo_category" />
    },
    {
        id: 16,
        name: "Animación",
        link: "animation",
        icon: <AnimationIcon className="logo_category" />
    },
    {
        id: 35,
        name: "Comedia",
        link: "comedy",
        icon: <ComedyIcon className="logo_category" />
    },
    {
        id: 80,
        name: "Crimen",
        link: "crime",
        icon: <CrimeIcon className="logo_category" />
    },
    {
        id: 99,
        name: "Documental",
        link: "documentary",
        icon: <DocumentaryIcon className="logo_category" />
    },
    {
        id: 18,
        name: "Drama",
        link: "drama",
        icon: <DramaIcon className="logo_category" />
    },
    {
        id: 10751,
        name: "Familia",
        link: "family",
        icon: <FamilyIcon className="logo_category" />
    },
    {
        id: 14,
        name: "Fantasía",
        link: "fantasy",
        icon: <FantasyIcon className="logo_category" />
    },
    {
        id: 36,
        name: "Historia",
        link: "history",
        icon: <HistoryIcon className="logo_category" />
    },
    {
        id: 27,
        name: "Terror",
        link: "horror",
        icon: <HorrorIcon className="logo_category" />
    },
    {
        id: 10402,
        name: "Música",
        link: "music",
        icon: <MusicIcon className="logo_category" />
    },
    {
        id: 9648,
        name: "Misterio",
        link: "mystery",
        icon: <MysteryIcon className="logo_category" />
    },
    {
        id: 10749,
        name: "Romance",
        link: "romance",
        icon: <RomanceIcon className="logo_category" />
    },
    {
        id: 878,
        name: "Ciencia ficción",
        link: "science_fiction",
        icon: <SCIFiIcon className="logo_category" />
    },
    {
        id: 10770,
        name: "Película de TV",
        link: "tv_movie",
        icon: <TVMovieIcon className="logo_category" />
    },
    {
        id: 53,
        name: "Suspenso",
        link: "thriller",
        icon: <ThrillerIcon className="logo_category" />
    },
    {
        id: 10752,
        name: "Bélica",
        link: "war",
        icon: <WarIcon className="logo_category" />
    },
    {
        id: 37,
        name: "Western",
        link: "western",
        icon: <WesternIcon className="logo_category" />
    }
]

export const CategoriesSeries = [
    {
        id: 10759,
        name: "Acción & Aventura",
        link: "action",
        icon: <AdventureIcon className="logo_category" />
    },
    {
        id: 16,
        name: "Animación",
        link: "action",
        icon: <AnimationIcon className="logo_category" />
    },
    {
        id: 35,
        name: "Comedia",
        link: "action",
        icon: <ComedyIcon className="logo_category" />
    },
    {
        id: 80,
        name: "Crimen",
        link: "action",
        icon: <CrimeIcon className="logo_category" />
    },
    {
        id: 99,
        name: "Documental",
        link: "action",
        icon: <DocumentaryIcon className="logo_category" />
    },
    {
        id: 18,
        name: "Drama",
        link: "action",
        icon: <DramaIcon className="logo_category" />
    },
    {
        id: 10751,
        name: "Familia",
        link: "action",
        icon: <FamilyIcon className="logo_category" />
    },
    {
        id: 10762,
        name: "Kids",
        link: "action",
        icon: <KidIcon className="logo_category" />
    },
    {
        id: 9648,
        name: "Misterio",
        link: "action",
        icon: <MysteryIcon className="logo_category" />
    },
    {
        id: 10763,
        name: "Noticias",
        link: "news",
        icon: <NewsIcon className="logo_category" />
    },
    {
        id: 10764,
        name: "Reality",
        link: "reality",
        icon: <RealityIcon className="logo_category" />
    },
    {
        id: 10765,
        name: "Ciencia ficción",
        link: "science_fiction",
        icon: <SCIFiIcon className="logo_category" />
    },
    {
        id: 10766,
        name: "Telenovelas",
        link: "soap",
        icon: <SoapIcon className="logo_category" />
    },
    {
        id: 10767,
        name: "Talk",
        link: "action",
        icon: <TalkIcon className="logo_category" />
    },
    {
        id: 10768,
        name: "Bélica",
        link: "war",
        icon: <WarIcon className="logo_category" />
    },
    {
        id: 37,
        name: "Western",
        link: "weatern",
        icon: <WesternIcon className="logo_category" />
    }
]



export const BASE_URL_IMG = 'https://image.tmdb.org/t/p/original'
export const BASE_URL_IMG_CUSTOM = 'https://image.tmdb.org/t/p/'

export const URL_IMAGE_NOTPHOTO = "https://raw.githubusercontent.com/AletzMan/ImagesStorage/refs/heads/main/film_data_hub/not_photo.png"
export const URL_IMAGE_NOTPHOTO_PROFILE = "https://raw.githubusercontent.com/AletzMan/ImagesStorage/refs/heads/main/film_data_hub/not-photo.webp"
export const URL_IMAGE_NOTCOVER = "https://raw.githubusercontent.com/AletzMan/ImagesStorage/refs/heads/main/film_data_hub/not_cover.webp"

export const countryFlags = [
    {
        "country": "Afganistán",
        "countryCode": 93,
        "code": "AF",
        "flag": "https://flagcdn.com/af.svg",
        "emoji": "🇦🇫",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["AFG", "Afghanistan", "Afganistán"],
    },
    {
        "country": "Albania",
        "countryCode": 355,
        "code": "AL",
        "flag": "https://flagcdn.com/al.svg",
        "emoji": "🇦🇱",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ALB", "Albania", "Albania"],
    },
    {
        "country": "Alemania",
        "countryCode": 49,
        "code": "DE",
        "flag": "https://flagcdn.com/de.svg",
        "emoji": "🇩🇪",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["DEU", "Germany", "Alemania"],
    },
    {
        "country": "Andorra",
        "countryCode": 376,
        "code": "AD",
        "flag": "https://flagcdn.com/ad.svg",
        "emoji": "🇦🇩",
        "latinAmerica": false,
        "phoneLength": 6,
        "abbreviations": ["AND", "Andorra", "Andorra"],
    },
    {
        "country": "Angola",
        "countryCode": 244,
        "code": "AO",
        "flag": "https://flagcdn.com/ao.svg",
        "emoji": "🇦🇴",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["AGO", "Angola", "Angola"],
    },
    {
        "country": "Antigua y Barbuda",
        "countryCode": 1268,
        "code": "AG",
        "flag": "https://flagcdn.com/ag.svg",
        "emoji": "🇦🇬",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["ATG", "Antigua and Barbuda", "Antigua y Barbuda"],
    },
    {
        "country": "Arabia Saudita",
        "countryCode": 966,
        "code": "SA",
        "flag": "https://flagcdn.com/sa.svg",
        "emoji": "🇸🇦",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["SAU", "Saudi Arabia", "Arabia Saudita"],
    },
    {
        "country": "Argelia",
        "countryCode": 213,
        "code": "DZ",
        "flag": "https://flagcdn.com/dz.svg",
        "emoji": "🇩🇿",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["DZA", "Algeria", "Argelia"],
    },
    {
        "country": "Argentina",
        "countryCode": 54,
        "code": "AR",
        "flag": "https://flagcdn.com/ar.svg",
        "emoji": "🇦🇷",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["ARG", "Argentina", "Argentina"],
    },
    {
        "country": "Armenia",
        "countryCode": 374,
        "code": "AM",
        "flag": "https://flagcdn.com/am.svg",
        "emoji": "🇦🇲",
        "latinAmerica": false,
        "phoneLength": 6,
        "abbreviations": ["ARM", "Armenia", "Armenia"],
    },
    {
        "country": "Australia",
        "countryCode": 61,
        "code": "AU",
        "flag": "https://flagcdn.com/au.svg",
        "emoji": "🇦🇺",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["AUS", "Australia", "Australia"],
    },
    {
        "country": "Austria",
        "countryCode": 43,
        "code": "AT",
        "flag": "https://flagcdn.com/at.svg",
        "emoji": "🇦🇹",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["AUT", "Austria", "Austria"],
    },
    {
        "country": "Azerbaiyán",
        "countryCode": 994,
        "code": "AZ",
        "flag": "https://flagcdn.com/az.svg",
        "emoji": "🇦🇿",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["AZE", "Azerbaijan", "Azerbaiyán"],
    },
    {
        "country": "Bahamas",
        "countryCode": 1242,
        "code": "BS",
        "flag": "https://flagcdn.com/bs.svg",
        "emoji": "🇧🇸",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["BHS", "Bahamas", "Bahamas"],
    },
    {
        "country": "Bangladés",
        "countryCode": 880,
        "code": "BD",
        "flag": "https://flagcdn.com/bd.svg",
        "emoji": "🇧🇩",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["BGD", "Bangladesh", "Bangladés"],
    },
    {
        "country": "Barbados",
        "countryCode": 1246,
        "code": "BB",
        "flag": "https://flagcdn.com/bb.svg",
        "emoji": "🇧🇧",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["BRB", "Barbados", "Barbados"],
    },
    {
        "country": "Baréin",
        "countryCode": 973,
        "code": "BH",
        "flag": "https://flagcdn.com/bh.svg",
        "emoji": "🇧🇭",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["BHR", "Bahrain", "Baréin"],
    },
    {
        "country": "Bélgica",
        "countryCode": 32,
        "code": "BE",
        "flag": "https://flagcdn.com/be.svg",
        "emoji": "🇧🇪",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["BEL", "Belgium", "Bélgica"],
    },
    {
        "country": "Belice",
        "countryCode": 501,
        "code": "BZ",
        "flag": "https://flagcdn.com/bz.svg",
        "emoji": "🇧🇿",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["BLZ", "Belize", "Belice"],
    },
    {
        "country": "Benín",
        "countryCode": 229,
        "code": "BJ",
        "flag": "https://flagcdn.com/bj.svg",
        "emoji": "🇧🇯",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["BEN", "Benin", "Benín"],
    },
    {
        "country": "Bielorrusia",
        "countryCode": 375,
        "code": "BY",
        "flag": "https://flagcdn.com/by.svg",
        "emoji": "🇧🇾",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["BLR", "Belarus", "Bielorrusia"],
    },
    {
        "country": "Birmania",
        "countryCode": 95,
        "code": "MM",
        "flag": "https://flagcdn.com/mm.svg",
        "emoji": "🇲🇲",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["MMR", "Myanmar", "Birmania"],
    },
    {
        "country": "Bolivia",
        "countryCode": 591,
        "code": "BO",
        "flag": "https://flagcdn.com/bo.svg",
        "emoji": "🇧🇴",
        "latinAmerica": true,
        "phoneLength": 9,
        "abbreviations": ["BOL", "Bolivia", "Bolivia"],
    },
    {
        "country": "Bosnia y Herzegovina",
        "countryCode": 387,
        "code": "BA",
        "flag": "https://flagcdn.com/ba.svg",
        "emoji": "🇧🇦",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["BIH", "Bosnia and Herzegovina", "Bosnia y Herzegovina"],
    },
    {
        "country": "Botsuana",
        "countryCode": 267,
        "code": "BW",
        "flag": "https://flagcdn.com/bw.svg",
        "emoji": "🇧🇼",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["BWA", "Botswana", "Botsuana"],
    },
    {
        "country": "Brasil",
        "countryCode": 55,
        "code": "BR",
        "flag": "https://flagcdn.com/br.svg",
        "emoji": "🇧🇷",
        "latinAmerica": true,
        "phoneLength": 11,
        "abbreviations": ["BRA", "Brazil", "Brasil"],
    },
    {
        "country": "Brunéi",
        "countryCode": 673,
        "code": "BN",
        "flag": "https://flagcdn.com/bn.svg",
        "emoji": "🇧🇳",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["BRN", "Brunei", "Brunéi"],
    },
    {
        "country": "Bulgaria",
        "countryCode": 359,
        "code": "BG",
        "flag": "https://flagcdn.com/bg.svg",
        "emoji": "🇧🇬",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["BGR", "Bulgaria", "Bulgaria"],
    },
    {
        "country": "Burkina Faso",
        "countryCode": 226,
        "code": "BF",
        "flag": "https://flagcdn.com/bf.svg",
        "emoji": "🇧🇫",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["BFA", "Burkina Faso", "Burkina Faso"],
    },
    {
        "country": "Burundi",
        "countryCode": 257,
        "code": "BI",
        "flag": "https://flagcdn.com/bi.svg",
        "emoji": "🇧🇮",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["BDI", "Burundi", "Burundi"],
    },
    {
        "country": "Bután",
        "countryCode": 975,
        "code": "BT",
        "flag": "https://flagcdn.com/bt.svg",
        "emoji": "🇧🇹",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["BTN", "Bhutan", "Bután"],
    },
    {
        "country": "Cabo Verde",
        "countryCode": 238,
        "code": "CV",
        "flag": "https://flagcdn.com/cv.svg",
        "emoji": "🇨🇻",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["CPV", "Cabo Verde", "Cabo Verde"],
    },
    {
        "country": "Camboya",
        "countryCode": 855,
        "code": "KH",
        "flag": "https://flagcdn.com/kh.svg",
        "emoji": "🇰🇭",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["KHM", "Cambodia", "Camboya"],
    },
    {
        "country": "Camerún",
        "countryCode": 237,
        "code": "CM",
        "flag": "https://flagcdn.com/cm.svg",
        "emoji": "🇨🇲",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["CMR", "Cameroon", "Camerún"],
    },
    {
        "country": "Canadá",
        "countryCode": 1,
        "code": "CA",
        "flag": "https://flagcdn.com/ca.svg",
        "emoji": "🇨🇦",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["CAN", "Canada", "Canadá"],
    },
    {
        "country": "Catar",
        "countryCode": 974,
        "code": "QA",
        "flag": "https://flagcdn.com/qa.svg",
        "emoji": "🇶🇦",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["QAT", "Qatar", "Catar"],
    },
    {
        "country": "Chad",
        "countryCode": 235,
        "code": "TD",
        "flag": "https://flagcdn.com/td.svg",
        "emoji": "🇹🇩",
        "latinAmerica": false,
        "phoneLength": 6,
        "abbreviations": ["TCD", "Chad", "Chad"],
    },
    {
        "country": "Chile",
        "countryCode": 56,
        "code": "CL",
        "flag": "https://flagcdn.com/cl.svg",
        "emoji": "🇨🇱",
        "latinAmerica": true,
        "phoneLength": 9,
        "abbreviations": ["CHL", "Chile", "Chile"],
    },
    {
        "country": "China",
        "countryCode": 86,
        "code": "CN",
        "flag": "https://flagcdn.com/cn.svg",
        "emoji": "🇨🇳",
        "latinAmerica": false,
        "phoneLength": 11,
        "abbreviations": ["CHN", "China", "China"],
    },
    {
        "country": "Chipre",
        "countryCode": 357,
        "code": "CY",
        "flag": "https://flagcdn.com/cy.svg",
        "emoji": "🇨🇾",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["CYP", "Cyprus", "Chipre"],
    },
    {
        "country": "Colombia",
        "countryCode": 57,
        "code": "CO",
        "flag": "https://flagcdn.com/co.svg",
        "emoji": "🇨🇴",
        "latinAmerica": true,
        "phoneLength": 10,
        "abbreviations": ["COL", "Colombia", "Colombia"],
    },
    {
        "country": "Comoras",
        "countryCode": 269,
        "code": "KM",
        "flag": "https://flagcdn.com/km.svg",
        "emoji": "🇰🇲",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["COM", "Comoros", "Comoras"],
    },
    {
        "country": "Congo",
        "countryCode": 242,
        "code": "CG",
        "flag": "https://flagcdn.com/cg.svg",
        "emoji": "🇨🇬",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["COG", "Congo", "Congo"],
    },
    {
        "country": "Corea del Norte",
        "countryCode": 850,
        "code": "KP",
        "flag": "https://flagcdn.com/kp.svg",
        "emoji": "🇰🇵",
        "latinAmerica": false,
        "phoneLength": 13,
        "abbreviations": ["PRK", "North Korea", "Corea del Norte"],
    },
    {
        "country": "Corea del Sur",
        "countryCode": 82,
        "code": "KR",
        "flag": "https://flagcdn.com/kr.svg",
        "emoji": "🇰🇷",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["KOR", "South Korea", "Corea del Sur"],
    },
    {
        "country": "Costa de Marfil",
        "countryCode": 225,
        "code": "CI",
        "flag": "https://flagcdn.com/ci.svg",
        "emoji": "🇨🇮",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["CIV", "Ivory Coast", "Costa de Marfil"],
    },
    {
        "country": "Costa Rica",
        "countryCode": 506,
        "code": "CR",
        "flag": "https://flagcdn.com/cr.svg",
        "emoji": "🇨🇷",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["CRI", "Costa Rica", "Costa Rica"],
    },
    {
        "country": "Croacia",
        "countryCode": 385,
        "code": "HR",
        "flag": "https://flagcdn.com/hr.svg",
        "emoji": "🇭🇷",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["HRV", "Croatia", "Croacia"],
    },
    {
        "country": "Cuba",
        "countryCode": 53,
        "code": "CU",
        "flag": "https://flagcdn.com/cu.svg",
        "emoji": "🇨🇺",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["CUB", "Cuba", "Cuba"],
    },
    {
        "country": "Dinamarca",
        "countryCode": 45,
        "code": "DK",
        "flag": "https://flagcdn.com/dk.svg",
        "emoji": "🇩🇰",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["DNK", "Denmark", "Dinamarca"],
    },
    {
        "country": "Dominica",
        "countryCode": 1767,
        "code": "DM",
        "flag": "https://flagcdn.com/dm.svg",
        "emoji": "🇩🇲",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["DMA", "Dominica", "Dominica"],
    },
    {
        "country": "Ecuador",
        "countryCode": 593,
        "code": "EC",
        "flag": "https://flagcdn.com/ec.svg",
        "emoji": "🇪🇨",
        "latinAmerica": true,
        "phoneLength": 9,
        "abbreviations": ["ECU", "Ecuador", "Ecuador"],
    },
    {
        "country": "Egipto",
        "countryCode": 20,
        "code": "EG",
        "flag": "https://flagcdn.com/eg.svg",
        "emoji": "🇪🇬",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["EGY", "Egypt", "Egipto"],
    },
    {
        "country": "El Salvador",
        "countryCode": 503,
        "code": "SV",
        "flag": "https://flagcdn.com/sv.svg",
        "emoji": "🇸🇻",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["SLV", "El Salvador", "El Salvador"],
    },
    {
        "country": "Emiratos Árabes Unidos",
        "countryCode": 971,
        "code": "AE",
        "flag": "https://flagcdn.com/ae.svg",
        "emoji": "🇦🇪",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ARE", "United Arab Emirates", "Emiratos Árabes Unidos"],
    },
    {
        "country": "Eritrea",
        "countryCode": 291,
        "code": "ER",
        "flag": "https://flagcdn.com/er.svg",
        "emoji": "🇪🇷",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["ERI", "Eritrea", "Eritrea"],
    },
    {
        "country": "Eslovaquia",
        "countryCode": 421,
        "code": "SK",
        "flag": "https://flagcdn.com/sk.svg",
        "emoji": "🇸🇰",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["SVK", "Slovakia", "Eslovaquia"],
    },
    {
        "country": "Eslovenia",
        "countryCode": 386,
        "code": "SI",
        "flag": "https://flagcdn.com/si.svg",
        "emoji": "🇸🇮",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["SVN", "Slovenia", "Eslovenia"],
    },
    {
        "country": "España",
        "countryCode": 34,
        "code": "ES",
        "flag": "https://flagcdn.com/es.svg",
        "emoji": "🇪🇸",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ESP", "Spain", "España"],
    },
    {
        "country": "Estados Unidos",
        "countryCode": 1,
        "code": "US",
        "flag": "https://flagcdn.com/us.svg",
        "emoji": "🇺🇸",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["USA", "United States", "Estados Unidos"],
    },
    {
        "country": "Estonia",
        "countryCode": 372,
        "code": "EE",
        "flag": "https://flagcdn.com/ee.svg",
        "emoji": "🇪🇪",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["EST", "Estonia", "Estonia"],
    },
    {
        "country": "Etiopía",
        "countryCode": 251,
        "code": "ET",
        "flag": "https://flagcdn.com/et.svg",
        "emoji": "🇪🇹",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ETH", "Ethiopia", "Etiopía"],
    },
    {
        "country": "Filipinas",
        "countryCode": 63,
        "code": "PH",
        "flag": "https://flagcdn.com/ph.svg",
        "emoji": "🇵🇭",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["PHL", "Philippines", "Filipinas"],
    },
    {
        "country": "Finlandia",
        "countryCode": 358,
        "code": "FI",
        "flag": "https://flagcdn.com/fi.svg",
        "emoji": "🇫🇮",
        "latinAmerica": false,
        "phoneLength": 11,
        "abbreviations": ["FIN", "Finland", "Finlandia"],
    },
    {
        "country": "Fiyi",
        "countryCode": 679,
        "code": "FJ",
        "flag": "https://flagcdn.com/fj.svg",
        "emoji": "🇫🇯",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["FJI", "Fiji", "Fiyi"],
    },
    {
        "country": "Francia",
        "countryCode": 33,
        "code": "FR",
        "flag": "https://flagcdn.com/fr.svg",
        "emoji": "🇫🇷",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["FRA", "France", "Francia"],
    },
    {
        "country": "Gabón",
        "countryCode": 241,
        "code": "GA",
        "flag": "https://flagcdn.com/ga.svg",
        "emoji": "🇬🇦",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["GAB", "Gabon", "Gabón"],
    },
    {
        "country": "Gambia",
        "countryCode": 220,
        "code": "GM",
        "flag": "https://flagcdn.com/gm.svg",
        "emoji": "🇬🇲",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["GMB", "Gambia", "Gambia"],
    },
    {
        "country": "Georgia",
        "countryCode": 995,
        "code": "GE",
        "flag": "https://flagcdn.com/ge.svg",
        "emoji": "🇬🇪",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["GEO", "Georgia", "Georgia"],
    },
    {
        "country": "Ghana",
        "countryCode": 233,
        "code": "GH",
        "flag": "https://flagcdn.com/gh.svg",
        "emoji": "🇬🇭",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["GHA", "Ghana", "Ghana"],
    },
    {
        "country": "Granada",
        "countryCode": 1473,
        "code": "GD",
        "flag": "https://flagcdn.com/gd.svg",
        "emoji": "🇬🇩",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["GRD", "Grenada", "Granada"],
    },
    {
        "country": "Grecia",
        "countryCode": 30,
        "code": "GR",
        "flag": "https://flagcdn.com/gr.svg",
        "emoji": "🇬🇷",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["GRC", "Greece", "Grecia"],
    },
    {
        "country": "Guatemala",
        "countryCode": 502,
        "code": "GT",
        "flag": "https://flagcdn.com/gt.svg",
        "emoji": "🇬🇹",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["GTM", "Guatemala", "Guatemala"],
    },
    {
        "country": "Guinea",
        "countryCode": 224,
        "code": "GN",
        "flag": "https://flagcdn.com/gn.svg",
        "emoji": "🇬🇳",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["GIN", "Guinea", "Guinea"],
    },
    {
        "country": "Guinea-Bisáu",
        "countryCode": 245,
        "code": "GW",
        "flag": "https://flagcdn.com/gw.svg",
        "emoji": "🇬🇼",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["GNB", "Guinea-Bissau", "Guinea-Bisáu"],
    },
    {
        "country": "Guinea Ecuatorial",
        "countryCode": 240,
        "code": "GQ",
        "flag": "https://flagcdn.com/gq.svg",
        "emoji": "🇬🇶",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["GNQ", "Equatorial Guinea", "Guinea Ecuatorial"],
    },
    {
        "country": "Guyana",
        "countryCode": 592,
        "code": "GY",
        "flag": "https://flagcdn.com/gy.svg",
        "emoji": "🇬🇾",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["GUY", "Guyana", "Guyana"],
    },
    {
        "country": "Haití",
        "countryCode": 509,
        "code": "HT",
        "flag": "https://flagcdn.com/ht.svg",
        "emoji": "🇭🇹",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["HTI", "Haiti", "Haití"],
    },
    {
        "country": "Honduras",
        "countryCode": 504,
        "code": "HN",
        "flag": "https://flagcdn.com/hn.svg",
        "emoji": "🇭🇳",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["HND", "Honduras", "Honduras"],
    },
    {
        "country": "Hungría",
        "countryCode": 36,
        "code": "HU",
        "flag": "https://flagcdn.com/hu.svg",
        "emoji": "🇭🇺",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["HUN", "Hungary", "Hungría"],
    },
    {
        "country": "India",
        "countryCode": 91,
        "code": "IN",
        "flag": "https://flagcdn.com/in.svg",
        "emoji": "🇮🇳",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["IND", "India", "India"],
    },
    {
        "country": "Indonesia",
        "countryCode": 62,
        "code": "ID",
        "flag": "https://flagcdn.com/id.svg",
        "emoji": "🇮🇩",
        "latinAmerica": false,
        "phoneLength": 11,
        "abbreviations": ["IDN", "Indonesia", "Indonesia"],
    },
    {
        "country": "Irak",
        "countryCode": 964,
        "code": "IQ",
        "flag": "https://flagcdn.com/iq.svg",
        "emoji": "🇮🇶",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["IRQ", "Iraq", "Irak"],
    },
    {
        "country": "Irán",
        "countryCode": 98,
        "code": "IR",
        "flag": "https://flagcdn.com/ir.svg",
        "emoji": "🇮🇷",
        "latinAmerica": false,
        "phoneLength": 11,
        "abbreviations": ["IRN", "Iran", "Irán"],
    },
    {
        "country": "Irlanda",
        "countryCode": 353,
        "code": "IE",
        "flag": "https://flagcdn.com/ie.svg",
        "emoji": "🇮🇪",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["IRL", "Ireland", "Irlanda"],
    },
    {
        "country": "Islandia",
        "countryCode": 354,
        "code": "IS",
        "flag": "https://flagcdn.com/is.svg",
        "emoji": "🇮🇸",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["ISL", "Iceland", "Islandia"],
    },
    {
        "country": "Islas Marshall",
        "countryCode": 692,
        "code": "MH",
        "flag": "https://flagcdn.com/mh.svg",
        "emoji": "🇲🇭",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["MHL", "Marshall Islands", "Islas Marshall"],
    },
    {
        "country": "Islas Salomón",
        "countryCode": 677,
        "code": "SB",
        "flag": "https://flagcdn.com/sb.svg",
        "emoji": "🇸🇧",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SLB", "Solomon Islands", "Islas Salomón"],
    },
    {
        "country": "Israel",
        "countryCode": 972,
        "code": "IL",
        "flag": "https://flagcdn.com/il.svg",
        "emoji": "🇮🇱",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ISR", "Israel", "Israel"],
    },
    {
        "country": "Italia",
        "countryCode": 39,
        "code": "IT",
        "flag": "https://flagcdn.com/it.svg",
        "emoji": "🇮🇹",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["ITA", "Italy", "Italia"],
    },
    {
        "country": "Jamaica",
        "countryCode": 1876,
        "code": "JM",
        "flag": "https://flagcdn.com/jm.svg",
        "emoji": "🇯🇲",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["JAM", "Jamaica", "Jamaica"],
    },
    {
        "country": "Japón",
        "countryCode": 81,
        "code": "JP",
        "flag": "https://flagcdn.com/jp.svg",
        "emoji": "🇯🇵",
        "latinAmerica": false,
        "phoneLength": 0,
        "abbreviations": ["JPN", "Japan", "Japón"],
    },
    {
        "country": "Jordania",
        "countryCode": 962,
        "code": "JO",
        "flag": "https://flagcdn.com/jo.svg",
        "emoji": "🇯🇴",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["JOR", "Jordan", "Jordania"],
    },
    {
        "country": "Kazajistán",
        "countryCode": 7,
        "code": "KZ",
        "flag": "https://flagcdn.com/kz.svg",
        "emoji": "🇰🇿",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["KAZ", "Kazakhstan", "Kazajistán"],
    },
    {
        "country": "Kenia",
        "countryCode": 254,
        "code": "KE",
        "flag": "https://flagcdn.com/ke.svg",
        "emoji": "🇰🇪",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["KEN", "Kenya", "Kenia"],
    },
    {
        "country": "Kirguistán",
        "countryCode": 996,
        "code": "KG",
        "flag": "https://flagcdn.com/kg.svg",
        "emoji": "🇰🇬",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["KGZ", "Kyrgyzstan", "Kirguistán"],
    },
    {
        "country": "Kiribati",
        "countryCode": 686,
        "code": "KI",
        "flag": "https://flagcdn.com/ki.svg",
        "emoji": "🇰🇮",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["KIR", "Kiribati", "Kiribati"],
    },
    {
        "country": "Kuwait",
        "countryCode": 965,
        "code": "KW",
        "flag": "https://flagcdn.com/kw.svg",
        "emoji": "🇰🇼",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["KWT", "Kuwait", "Kuwait"],
    },
    {
        "country": "Laos",
        "countryCode": 856,
        "code": "LA",
        "flag": "https://flagcdn.com/la.svg",
        "emoji": "🇱🇦",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["LAO", "Laos", "Laos"],
    },
    {
        "country": "Lesoto",
        "countryCode": 266,
        "code": "LS",
        "flag": "https://flagcdn.com/ls.svg",
        "emoji": "🇱🇸",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["LSO", "Lesotho", "Lesoto"],
    },
    {
        "country": "Letonia",
        "countryCode": 371,
        "code": "LV",
        "flag": "https://flagcdn.com/lv.svg",
        "emoji": "🇱🇻",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["LVA", "Latvia", "Letonia"],
    },
    {
        "country": "Líbano",
        "countryCode": 961,
        "code": "LB",
        "flag": "https://flagcdn.com/lb.svg",
        "emoji": "🇱🇧",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["LBN", "Lebanon", "Líbano"],
    },
    {
        "country": "Liberia",
        "countryCode": 231,
        "code": "LR",
        "flag": "https://flagcdn.com/lr.svg",
        "emoji": "🇱🇷",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["LBR", "Liberia", "Liberia"],
    },
    {
        "country": "Libia",
        "countryCode": 218,
        "code": "LY",
        "flag": "https://flagcdn.com/ly.svg",
        "emoji": "🇱🇾",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["LBY", "Libya", "Libia"],
    },
    {
        "country": "Liechtenstein",
        "countryCode": 423,
        "code": "LI",
        "flag": "https://flagcdn.com/li.svg",
        "emoji": "🇱🇮",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["LIE", "Liechtenstein", "Liechtenstein"],
    },
    {
        "country": "Lituania",
        "countryCode": 370,
        "code": "LT",
        "flag": "https://flagcdn.com/lt.svg",
        "emoji": "🇱🇹",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["LTU", "Lithuania", "Lituania"],
    },
    {
        "country": "Luxemburgo",
        "countryCode": 352,
        "code": "LU",
        "flag": "https://flagcdn.com/lu.svg",
        "emoji": "🇱🇺",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["LUX", "Luxembourg", "Luxemburgo"],
    },
    {
        "country": "Madagascar",
        "countryCode": 261,
        "code": "MG",
        "flag": "https://flagcdn.com/mg.svg",
        "emoji": "🇲🇬",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["MDG", "Madagascar", "Madagascar"],
    },
    {
        "country": "Malasia",
        "countryCode": 60,
        "code": "MY",
        "flag": "https://flagcdn.com/my.svg",
        "emoji": "🇲🇾",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["MYS", "Malaysia", "Malasia"],
    },
    {
        "country": "Malaui",
        "countryCode": 265,
        "code": "MW",
        "flag": "https://flagcdn.com/mw.svg",
        "emoji": "🇲🇼",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["MWI", "Malawi", "Malaui"],
    },
    {
        "country": "Maldivas",
        "countryCode": 960,
        "code": "MV",
        "flag": "https://flagcdn.com/mv.svg",
        "emoji": "🇲🇻",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["MDV", "Maldives", "Maldivas"],
    },
    {
        "country": "Malí",
        "countryCode": 223,
        "code": "ML",
        "flag": "https://flagcdn.com/ml.svg",
        "emoji": "🇲🇱",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MLI", "Mali", "Malí"],
    },
    {
        "country": "Malta",
        "countryCode": 356,
        "code": "MT",
        "flag": "https://flagcdn.com/mt.svg",
        "emoji": "🇲🇹",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MLT", "Malta", "Malta"],
    },
    {
        "country": "Marruecos",
        "countryCode": 212,
        "code": "MA",
        "flag": "https://flagcdn.com/ma.svg",
        "emoji": "🇲🇦",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["MAR", "Morocco", "Marruecos"],
    },
    {
        "country": "Mauricio",
        "countryCode": 230,
        "code": "MU",
        "flag": "https://flagcdn.com/mu.svg",
        "emoji": "🇲🇺",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MUS", "Mauritius", "Mauricio"],
    },
    {
        "country": "Mauritania",
        "countryCode": 222,
        "code": "MR",
        "flag": "https://flagcdn.com/mr.svg",
        "emoji": "🇲🇷",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MRT", "Mauritania", "Mauritania"],
    },
    {
        "country": "México",
        "countryCode": 52,
        "code": "MX",
        "flag": "https://flagcdn.com/mx.svg",
        "emoji": "🇲🇽",
        "latinAmerica": true,
        "phoneLength": 10,
        "abbreviations": ["MEX", "Mexico", "México"],
    },
    {
        "country": "Micronesia",
        "countryCode": 691,
        "code": "FM",
        "flag": "https://flagcdn.com/fm.svg",
        "emoji": "🇫🇲",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["FSM", "Micronesia", "Micronesia"],
    },
    {
        "country": "Moldavia",
        "countryCode": 373,
        "code": "MD",
        "flag": "https://flagcdn.com/md.svg",
        "emoji": "🇲🇩",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MDA", "Moldova", "Moldavia"],
    },
    {
        "country": "Mónaco",
        "countryCode": 377,
        "code": "MC",
        "flag": "https://flagcdn.com/mc.svg",
        "emoji": "🇲🇨",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MCO", "Monaco", "Mónaco"],
    },
    {
        "country": "Mongolia",
        "countryCode": 976,
        "code": "MN",
        "flag": "https://flagcdn.com/mn.svg",
        "emoji": "🇲🇳",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MNG", "Mongolia", "Mongolia"],
    },
    {
        "country": "Montenegro",
        "countryCode": 382,
        "code": "ME",
        "flag": "https://flagcdn.com/me.svg",
        "emoji": "🇲🇪",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["MNE", "Montenegro", "Montenegro"],
    },
    {
        "country": "Mozambique",
        "countryCode": 258,
        "code": "MZ",
        "flag": "https://flagcdn.com/mz.svg",
        "emoji": "🇲🇿",
        "latinAmerica": false,
        "phoneLength": 12,
        "abbreviations": ["MOZ", "Mozambique", "Mozambique"],
    },
    {
        "country": "Namibia",
        "countryCode": 264,
        "code": "NA",
        "flag": "https://flagcdn.com/na.svg",
        "emoji": "🇳🇦",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["NAM", "Namibia", "Namibia"],
    },
    {
        "country": "Nauru",
        "countryCode": 674,
        "code": "NR",
        "flag": "https://flagcdn.com/nr.svg",
        "emoji": "🇳🇷",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["NRU", "Nauru", "Nauru"],
    },
    {
        "country": "Nepal",
        "countryCode": 977,
        "code": "NP",
        "flag": "https://flagcdn.com/np.svg",
        "emoji": "🇳🇵",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["NPL", "Nepal", "Nepal"],
    },
    {
        "country": "Nicaragua",
        "countryCode": 505,
        "code": "NI",
        "flag": "https://flagcdn.com/ni.svg",
        "emoji": "🇳🇮",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["NIC", "Nicaragua", "Nicaragua"],
    },
    {
        "country": "Níger",
        "countryCode": 227,
        "code": "NE",
        "flag": "https://flagcdn.com/ne.svg",
        "emoji": "🇳🇪",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["NER", "Niger", "Níger"],
    },
    {
        "country": "Nigeria",
        "countryCode": 234,
        "code": "NG",
        "flag": "https://flagcdn.com/ng.svg",
        "emoji": "🇳🇬",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["NGA", "Nigeria", "Nigeria"],
    },
    {
        "country": "Noruega",
        "countryCode": 47,
        "code": "NO",
        "flag": "https://flagcdn.com/no.svg",
        "emoji": "🇳🇴",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["NOR", "Norway", "Noruega"],
    },
    {
        "country": "Nueva Zelanda",
        "countryCode": 64,
        "code": "NZ",
        "flag": "https://flagcdn.com/nz.svg",
        "emoji": "🇳🇿",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["NZL", "New Zealand", "Nueva Zelanda"],
    },
    {
        "country": "Omán",
        "countryCode": 968,
        "code": "OM",
        "flag": "https://flagcdn.com/om.svg",
        "emoji": "🇴🇲",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["OMN", "Oman", "Omán"],
    },
    {
        "country": "Países Bajos",
        "countryCode": 31,
        "code": "NL",
        "flag": "https://flagcdn.com/nl.svg",
        "emoji": "🇳🇱",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["NLD", "Netherlands", "Países Bajos"],
    },
    {
        "country": "Pakistán",
        "countryCode": 92,
        "code": "PK",
        "flag": "https://flagcdn.com/pk.svg",
        "emoji": "🇵🇰",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["PAK", "Pakistan", "Pakistán"],
    },
    {
        "country": "Palaos",
        "countryCode": 680,
        "code": "PW",
        "flag": "https://flagcdn.com/pw.svg",
        "emoji": "🇵🇼",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["PLW", "Palau", "Palaos"],
    },
    {
        "country": "Panamá",
        "countryCode": 507,
        "code": "PA",
        "flag": "https://flagcdn.com/pa.svg",
        "emoji": "🇵🇦",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["PAN", "Panama", "Panamá"],
    },
    {
        "country": "Papúa Nueva Guinea",
        "countryCode": 675,
        "code": "PG",
        "flag": "https://flagcdn.com/pg.svg",
        "emoji": "🇵🇬",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["PNG", "Papua New Guinea", "Papúa Nueva Guinea"],
    },
    {
        "country": "Paraguay",
        "countryCode": 595,
        "code": "PY",
        "flag": "https://flagcdn.com/py.svg",
        "emoji": "🇵🇾",
        "latinAmerica": true,
        "phoneLength": 9,
        "abbreviations": ["PRY", "Paraguay", "Paraguay"],
    },
    {
        "country": "Perú",
        "countryCode": 51,
        "code": "PE",
        "flag": "https://flagcdn.com/pe.svg",
        "emoji": "🇵🇪",
        "latinAmerica": true,
        "phoneLength": 9,
        "abbreviations": ["PER", "Peru", "Perú"],
    },
    {
        "country": "Polonia",
        "countryCode": 48,
        "code": "PL",
        "flag": "https://flagcdn.com/pl.svg",
        "emoji": "🇵🇱",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["POL", "Poland", "Polonia"],
    },
    {
        "country": "Portugal",
        "countryCode": 351,
        "code": "PT",
        "flag": "https://flagcdn.com/pt.svg",
        "emoji": "🇵🇹",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["PRT", "Portugal", "Portugal"],
    },
    {
        "country": "Reino Unido",
        "countryCode": 44,
        "code": "GB",
        "flag": "https://flagcdn.com/gb.svg",
        "emoji": "🇬🇧",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["GBR", "United Kingdom", "Reino Unido", "UK", "England"],
    },
    {
        "country": "República Centroafricana",
        "countryCode": 236,
        "code": "CF",
        "flag": "https://flagcdn.com/cf.svg",
        "emoji": "🇨🇫",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["CAF", "Central African Republic", "República Centroafricana"],
    },
    {
        "country": "República Checa",
        "countryCode": 420,
        "code": "CZ",
        "flag": "https://flagcdn.com/cz.svg",
        "emoji": "🇨🇿",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["CZE", "Czech Republic", "República Checa"],
    },
    {
        "country": "República del Congo",
        "countryCode": 243,
        "code": "CD",
        "flag": "https://flagcdn.com/cd.svg",
        "emoji": "🇨🇩",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["COD", "Democratic Republic of the Congo", "República del Congo"],
    },
    {
        "country": "República Dominicana",
        "countryCode": 1809,
        "code": "DO",
        "flag": "https://flagcdn.com/do.svg",
        "emoji": "🇩🇴",
        "latinAmerica": true,
        "phoneLength": 10,
        "abbreviations": ["DOM", "Dominican Republic", "República Dominicana"],
    },
    {
        "country": "Ruanda",
        "countryCode": 250,
        "code": "RW",
        "flag": "https://flagcdn.com/rw.svg",
        "emoji": "🇷🇼",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["RWA", "Rwanda", "Ruanda"],
    },
    {
        "country": "Rumania",
        "countryCode": 40,
        "code": "RO",
        "flag": "https://flagcdn.com/ro.svg",
        "emoji": "🇷🇴",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["ROU", "Romania", "Rumania"],
    },
    {
        "country": "Rusia",
        "countryCode": 7,
        "code": "RU",
        "flag": "https://flagcdn.com/ru.svg",
        "emoji": "🇷🇺",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["RUS", "Russia", "Rusia"],
    },
    {
        "country": "Samoa",
        "countryCode": 685,
        "code": "WS",
        "flag": "https://flagcdn.com/ws.svg",
        "emoji": "🇼🇸",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["WSM", "Samoa", "Samoa"],
    },
    {
        "country": "San Cristóbal y Nieves",
        "countryCode": 1869,
        "code": "KN",
        "flag": "https://flagcdn.com/kn.svg",
        "emoji": "🇰🇳",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["KNA", "Saint Kitts and Nevis", "San Cristóbal y Nieves"],
    },
    {
        "country": "San Marino",
        "countryCode": 378,
        "code": "SM",
        "flag": "https://flagcdn.com/sm.svg",
        "emoji": "🇸🇲",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["SMR", "San Marino", "San Marino"],
    },
    {
        "country": "Santa Lucía",
        "countryCode": 1758,
        "code": "LC",
        "flag": "https://flagcdn.com/lc.svg",
        "emoji": "🇱🇨",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["LCA", "Saint Lucia", "Santa Lucía"],
    },
    {
        "country": "Santo Tomé y Príncipe",
        "countryCode": 239,
        "code": "ST",
        "flag": "https://flagcdn.com/st.svg",
        "emoji": "🇸🇹",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["STP", "Sao Tome and Principe", "Santo Tomé y Príncipe"],
    },
    {
        "country": "San Vicente y las Granadinas",
        "countryCode": 1784,
        "code": "VC",
        "flag": "https://flagcdn.com/vc.svg",
        "emoji": "🇻🇨",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["VCT", "Saint Vincent and the Grenadines", "San Vicente y las Granadinas"],
    },
    {
        "country": "Senegal",
        "countryCode": 221,
        "code": "SN",
        "flag": "https://flagcdn.com/sn.svg",
        "emoji": "🇸🇳",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["SEN", "Senegal", "Senegal"],
    },
    {
        "country": "Serbia",
        "countryCode": 381,
        "code": "RS",
        "flag": "https://flagcdn.com/rs.svg",
        "emoji": "🇷🇸",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["SRB", "Serbia", "Serbia"],
    },
    {
        "country": "Seychelles",
        "countryCode": 248,
        "code": "SC",
        "flag": "https://flagcdn.com/sc.svg",
        "emoji": "🇸🇨",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SYC", "Seychelles", "Seychelles"],
    },
    {
        "country": "Sierra Leona",
        "countryCode": 232,
        "code": "SL",
        "flag": "https://flagcdn.com/sl.svg",
        "emoji": "🇸🇱",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["SLE", "Sierra Leone", "Sierra Leona"],
    },
    {
        "country": "Singapur",
        "countryCode": 65,
        "code": "SG",
        "flag": "https://flagcdn.com/sg.svg",
        "emoji": "🇸🇬",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["SGP", "Singapore", "Singapur"],
    },
    {
        "country": "Siria",
        "countryCode": 963,
        "code": "SY",
        "flag": "https://flagcdn.com/sy.svg",
        "emoji": "🇸🇾",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SYR", "Syria", "Siria"],
    },
    {
        "country": "Somalia",
        "countryCode": 252,
        "code": "SO",
        "flag": "https://flagcdn.com/so.svg",
        "emoji": "🇸🇴",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["SOM", "Somalia", "Somalia"],
    },
    {
        "country": "Sri Lanka",
        "countryCode": 94,
        "code": "LK",
        "flag": "https://flagcdn.com/lk.svg",
        "emoji": "🇱🇰",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["LKA", "Sri Lanka", "Sri Lanka"],
    },
    {
        "country": "Sudáfrica",
        "countryCode": 27,
        "code": "ZA",
        "flag": "https://flagcdn.com/za.svg",
        "emoji": "🇿🇦",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ZAF", "South Africa", "Sudáfrica"],
    },
    {
        "country": "Sudán",
        "countryCode": 249,
        "code": "SD",
        "flag": "https://flagcdn.com/sd.svg",
        "emoji": "🇸🇩",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SDN", "Sudan", "Sudán"],
    },
    {
        "country": "Sudán del Sur",
        "countryCode": 211,
        "code": "SS",
        "flag": "https://flagcdn.com/ss.svg",
        "emoji": "🇸🇸",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SSD", "South Sudan", "Sudán del Sur"],
    },
    {
        "country": "Suecia",
        "countryCode": 46,
        "code": "SE",
        "flag": "https://flagcdn.com/se.svg",
        "emoji": "🇸🇪",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SWE", "Sweden", "Suecia"],
    },
    {
        "country": "Suiza",
        "countryCode": 41,
        "code": "CH",
        "flag": "https://flagcdn.com/ch.svg",
        "emoji": "🇨🇭",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["CHE", "Switzerland", "Suiza"],
    },
    {
        "country": "Surinam",
        "countryCode": 597,
        "code": "SR",
        "flag": "https://flagcdn.com/sr.svg",
        "emoji": "🇸🇷",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["SUR", "Suriname", "Surinam"],
    },
    {
        "country": "Tailandia",
        "countryCode": 66,
        "code": "TH",
        "flag": "https://flagcdn.com/th.svg",
        "emoji": "🇹🇭",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["THA", "Thailand", "Tailandia"],
    },
    {
        "country": "Tanzania",
        "countryCode": 255,
        "code": "TZ",
        "flag": "https://flagcdn.com/tz.svg",
        "emoji": "🇹🇿",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["TZA", "Tanzania", "Tanzania"],
    },
    {
        "country": "Tayikistán",
        "countryCode": 992,
        "code": "TJ",
        "flag": "https://flagcdn.com/tj.svg",
        "emoji": "🇹🇯",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["TJK", "Tajikistan", "Tayikistán"],
    },
    {
        "country": "Timor Oriental",
        "countryCode": 670,
        "code": "TL",
        "flag": "https://flagcdn.com/tl.svg",
        "emoji": "🇹🇱",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["TLS", "Timor-Leste", "Timor Oriental"],
    },
    {
        "country": "Togo",
        "countryCode": 228,
        "code": "TG",
        "flag": "https://flagcdn.com/tg.svg",
        "emoji": "🇹🇬",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["TGO", "Togo", "Togo"],
    },
    {
        "country": "Tonga",
        "countryCode": 676,
        "code": "TO",
        "flag": "https://flagcdn.com/to.svg",
        "emoji": "🇹🇴",
        "latinAmerica": false,
        "phoneLength": 5,
        "abbreviations": ["TON", "Tonga", "Tonga"],
    },
    {
        "country": "Trinidad y Tobago",
        "countryCode": 1868,
        "code": "TT",
        "flag": "https://flagcdn.com/tt.svg",
        "emoji": "🇹🇹",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["TTO", "Trinidad and Tobago", "Trinidad y Tobago"],
    },
    {
        "country": "Túnez",
        "countryCode": 216,
        "code": "TN",
        "flag": "https://flagcdn.com/tn.svg",
        "emoji": "🇹🇳",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["TUN", "Tunisia", "Túnez"],
    },
    {
        "country": "Turkmenistán",
        "countryCode": 993,
        "code": "TM",
        "flag": "https://flagcdn.com/tm.svg",
        "emoji": "🇹🇲",
        "latinAmerica": false,
        "phoneLength": 8,
        "abbreviations": ["TKM", "Turkmenistan", "Turkmenistán"],
    },
    {
        "country": "Turquía",
        "countryCode": 90,
        "code": "TR",
        "flag": "https://flagcdn.com/tr.svg",
        "emoji": "🇹🇷",
        "latinAmerica": false,
        "phoneLength": 11,
        "abbreviations": ["TUR", "Turkey", "Turquía"],
    },
    {
        "country": "Tuvalu",
        "countryCode": 688,
        "code": "TV",
        "flag": "https://flagcdn.com/tv.svg",
        "emoji": "🇹🇻",
        "latinAmerica": false,
        "phoneLength": 5,
        "abbreviations": ["TUV", "Tuvalu", "Tuvalu"],
    },
    {
        "country": "Ucrania",
        "countryCode": 380,
        "code": "UA",
        "flag": "https://flagcdn.com/ua.svg",
        "emoji": "🇺🇦",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["UKR", "Ukraine", "Ucrania"],
    },
    {
        "country": "Uganda",
        "countryCode": 256,
        "code": "UG",
        "flag": "https://flagcdn.com/ug.svg",
        "emoji": "🇺🇬",
        "latinAmerica": false,
        "phoneLength": 7,
        "abbreviations": ["UGA", "Uganda", "Uganda"],
    },
    {
        "country": "Uruguay",
        "countryCode": 598,
        "code": "UY",
        "flag": "https://flagcdn.com/uy.svg",
        "emoji": "🇺🇾",
        "latinAmerica": true,
        "phoneLength": 8,
        "abbreviations": ["URY", "Uruguay", "Uruguay"],
    },
    {
        "country": "Uzbekistán",
        "countryCode": 998,
        "code": "UZ",
        "flag": "https://flagcdn.com/uz.svg",
        "emoji": "🇺🇿",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["UZB", "Uzbekistan", "Uzbekistán"],
    },
    {
        "country": "Vanuatu",
        "countryCode": 678,
        "code": "VU",
        "flag": "https://flagcdn.com/vu.svg",
        "emoji": "🇻🇺",
        "latinAmerica": false,
        "phoneLength": 5,
        "abbreviations": ["VUT", "Vanuatu", "Vanuatu"],
    },
    {
        "country": "Venezuela",
        "countryCode": 58,
        "code": "VE",
        "flag": "https://flagcdn.com/ve.svg",
        "emoji": "🇻🇪",
        "latinAmerica": true,
        "phoneLength": 7,
        "abbreviations": ["VEN", "Venezuela", "Venezuela"],
    },
    {
        "country": "Vietnam",
        "countryCode": 84,
        "code": "VN",
        "flag": "https://flagcdn.com/vn.svg",
        "emoji": "🇻🇳",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["VNM", "Vietnam", "Vietnam"],
    },
    {
        "country": "Yemen",
        "countryCode": 967,
        "code": "YE",
        "flag": "https://flagcdn.com/ye.svg",
        "emoji": "🇾🇪",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["YEM", "Yemen", "Yemen"],
    },
    {
        "country": "Yibuti",
        "countryCode": 253,
        "code": "DJ",
        "flag": "https://flagcdn.com/dj.svg",
        "emoji": "🇩🇯",
        "latinAmerica": false,
        "phoneLength": 10,
        "abbreviations": ["DJI", "Djibouti", "Yibuti"],
    },
    {
        "country": "Zambia",
        "countryCode": 260,
        "code": "ZM",
        "flag": "https://flagcdn.com/zm.svg",
        "emoji": "🇿🇲",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ZMB", "Zambia", "Zambia"],
    },
    {
        "country": "Zimbabue",
        "countryCode": 263,
        "code": "ZW",
        "flag": "https://flagcdn.com/zw.svg",
        "emoji": "🇿🇼",
        "latinAmerica": false,
        "phoneLength": 9,
        "abbreviations": ["ZWE", "Zimbabwe", "Zimbabue"],
    },
]

export const GetRegions = (): IPropertiesCombobox[] => {
    let options: IPropertiesCombobox[] = []
    countryFlags.forEach(country => {
        options.push({ option: country.country, value: country.code })
    })
    return options
}



export const OptionsDateLocal: Intl.DateTimeFormatOptions = {
    timeZone: "America/New_York",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    //weekday: "long"
    //hour: "2-digit",
    //minute: "2-digit",
    //second: "2-digit",
    //hour12: true, // Para usar el formato de 12 horas (AM/PM)
}

export const SmallDateLocal: Intl.DateTimeFormatOptions = {
    timeZone: "America/New_York",
    year: "numeric",
    month: "long",
    day: "numeric", // Para usar el formato de 12 horas (AM/PM)
}

export const LargeDateLocal: Intl.DateTimeFormatOptions = {
    timeZone: "America/New_York",
    year: "numeric",
    month: "long",
    day: "numeric",
}



export function getDepartmentTranslation(department: string, gender: number = 0): string {
    const translations: Record<string, { male: string; female: string; neutral: string }> = {
        "Acting": { male: "Actuación", female: "Actuación", neutral: "Actuación" },
        "Directing": { male: "Dirección", female: "Dirección", neutral: "Dirección" },
        "Production": { male: "Producción", female: "Producción", neutral: "Producción" },
        "Writing": { male: "Guion", female: "Guion", neutral: "Guion" },
        "Editing": { male: "Edición", female: "Edición", neutral: "Edición" },
        "Camera": { male: "Cámara", female: "Cámara", neutral: "Cámara" },
        "Sound": { male: "Sonido", female: "Sonido", neutral: "Sonido" },
        "Art": { male: "Arte", female: "Arte", neutral: "Arte" },
        "Costume & Make-Up": { male: "Vestuario y Maquillaje", female: "Vestuario y Maquillaje", neutral: "Vestuario y Maquillaje" },
        "Visual Effects": { male: "Efectos Visuales", female: "Efectos Visuales", neutral: "Efectos Visuales" },
        "Crew": { male: "Equipo Técnico", female: "Equipo Técnico", neutral: "Equipo Técnico" },
        "Lighting": { male: "Iluminación", female: "Iluminación", neutral: "Iluminación" },
        "Music": { male: "Música", female: "Música", neutral: "Música" }
    };

    const role = translations[department];
    if (!role) return department;

    switch (gender) {
        case 1:
            return role.female;
        case 2:
            return role.male;
        case 0:
        case 3:
        default:
            return role.neutral;
    }
}

export interface SocialIconResult {
    name: string;
    icon: string; // Ej: "FacebookIcon", "InstagramIcon", etc.
    url: string;
}

export interface SocialIconResult {
    name: string;
    icon: string;
    url: string;
}

export function getAvailableSocialLinks(socials?: Record<string, any> | null): SocialIconResult[] | null {
    // Si viene undefined o null, regresa null
    if (!socials) {
        return null;
    }

    const socialConfig: Record<string, { name: string; icon: string; baseUrl: string }> = {
        facebook_id: { name: "Facebook", icon: "ic:baseline-facebook", baseUrl: "https://www.facebook.com/" },
        instagram_id: { name: "Instagram", icon: "mdi:instagram", baseUrl: "https://www.instagram.com/" },
        tiktok_id: { name: "TikTok", icon: "ic:baseline-tiktok", baseUrl: "https://www.tiktok.com/@" },
        twitter_id: { name: "Twitter", icon: "mdi:twitter", baseUrl: "https://twitter.com/" },
        youtube_id: { name: "YouTube", icon: "mdi:youtube", baseUrl: "https://www.youtube.com/@" },
    };

    const results: SocialIconResult[] = [];

    for (const [key, value] of Object.entries(socials)) {
        if (socialConfig[key] && value && value !== "" && value !== 0) {
            const config = socialConfig[key];
            results.push({
                name: config.name,
                icon: config.icon,
                url: `${config.baseUrl}${value}`
            });
        }
    }

    // Si no hay ninguna red social válida, puedes decidir si regresa un array vacío [] o null.
    // Aquí regresa el array con los elementos encontrados.
    return results.length > 0 ? results : null;
}